# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tsf/Clion-2018.2.6/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/tsf/Clion-2018.2.6/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tsf/int-collector

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tsf/int-collector

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/tsf/Clion-2018.2.6/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tsf/Clion-2018.2.6/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tsf/int-collector/CMakeFiles /home/tsf/int-collector/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tsf/int-collector/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named collect

# Build rule for target.
collect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collect
.PHONY : collect

# fast build rule for target.
collect/fast:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/build
.PHONY : collect/fast

collect.o: collect.c.o

.PHONY : collect.o

# target to build an object file
collect.c.o:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/collect.c.o
.PHONY : collect.c.o

collect.i: collect.c.i

.PHONY : collect.i

# target to preprocess a source file
collect.c.i:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/collect.c.i
.PHONY : collect.c.i

collect.s: collect.c.s

.PHONY : collect.s

# target to generate assembly for a file
collect.c.s:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/collect.c.s
.PHONY : collect.c.s

sbuf.o: sbuf.c.o

.PHONY : sbuf.o

# target to build an object file
sbuf.c.o:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/sbuf.c.o
.PHONY : sbuf.c.o

sbuf.i: sbuf.c.i

.PHONY : sbuf.i

# target to preprocess a source file
sbuf.c.i:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/sbuf.c.i
.PHONY : sbuf.c.i

sbuf.s: sbuf.c.s

.PHONY : sbuf.s

# target to generate assembly for a file
sbuf.c.s:
	$(MAKE) -f CMakeFiles/collect.dir/build.make CMakeFiles/collect.dir/sbuf.c.s
.PHONY : sbuf.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... collect"
	@echo "... collect.o"
	@echo "... collect.i"
	@echo "... collect.s"
	@echo "... sbuf.o"
	@echo "... sbuf.i"
	@echo "... sbuf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

